# Generated by Django 4.2.27 on 2026-01-22 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_ticket_created', models.BooleanField(default=True, verbose_name='Email on Ticket Created')),
                ('email_ticket_assigned', models.BooleanField(default=True, verbose_name='Email on Ticket Assigned')),
                ('email_ticket_status_changed', models.BooleanField(default=True, verbose_name='Email on Status Changed')),
                ('email_ticket_comment', models.BooleanField(default=True, verbose_name='Email on New Comment')),
                ('email_sla_warning', models.BooleanField(default=True, verbose_name='Email on SLA Warning')),
                ('email_system', models.BooleanField(default=False, verbose_name='Email System Notifications')),
                ('inapp_ticket_created', models.BooleanField(default=True, verbose_name='In-App Ticket Created')),
                ('inapp_ticket_assigned', models.BooleanField(default=True, verbose_name='In-App Ticket Assigned')),
                ('inapp_ticket_status_changed', models.BooleanField(default=True, verbose_name='In-App Status Changed')),
                ('inapp_ticket_comment', models.BooleanField(default=True, verbose_name='In-App New Comment')),
                ('inapp_sla_warning', models.BooleanField(default=True, verbose_name='In-App SLA Warning')),
                ('inapp_system', models.BooleanField(default=True, verbose_name='In-App System Notifications')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ticket_created', 'Ticket Created'), ('ticket_assigned', 'Ticket Assigned'), ('ticket_status_changed', 'Ticket Status Changed'), ('ticket_comment', 'New Comment'), ('sla_warning', 'SLA Warning'), ('sla_breached', 'SLA Breached'), ('system', 'System Notification'), ('mention', 'You were mentioned')], default='system', max_length=30, verbose_name='Type')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Related Object Type')),
                ('related_object_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Related Object ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email Sent')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Email Sent At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_2d3764_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx'), models.Index(fields=['type'], name='notificatio_type_8a8a78_idx')],
            },
        ),
    ]
