# Generated by Django 4.2.27 on 2026-01-18 08:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TicketCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="tickets.ticketcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "new"),
                            ("assigned", "assigned"),
                            ("in_progress", "in_progress"),
                            ("pending_user", "pending_user"),
                            ("resolved", "resolved"),
                            ("closed", "closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("medium", "medium"),
                            ("high", "high"),
                            ("urgent", "urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("web", "web"),
                            ("email", "email"),
                            ("phone", "phone"),
                            ("mobile", "mobile"),
                        ],
                        default="web",
                        max_length=10,
                    ),
                ),
                ("requester_id", models.CharField(max_length=64)),
                (
                    "requester_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "requester_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("assignee_id", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "assignee_name",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                ("team_id", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "team_name",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                ("sla_response_deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "sla_resolution_deadline",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("sla_breached", models.BooleanField(default=False)),
                ("satisfaction_rating", models.IntegerField(blank=True, null=True)),
                ("satisfaction_comment", models.TextField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="tickets.ticketcategory",
                    ),
                ),
            ],
        ),
    ]
