# Generated by Django 4.2.27 on 2026-01-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="requester_email",
            field=models.EmailField(
                blank=True, default="dev@example.com", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="requester_id",
            field=models.CharField(blank=True, default="dev-user", max_length=64),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="requester_name",
            field=models.CharField(blank=True, default="Dev User", max_length=100),
        ),
    ]
