# Generated by Django 4.2.27 on 2026-01-18 10:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_ticketcomment"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("from_status", models.CharField(max_length=32)),
                ("to_status", models.CharField(max_length=32)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "changed_by_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "changed_by_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_histories",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["changed_at"],
            },
        ),
    ]
