# Generated by Django 4.2.27 on 2026-01-21 16:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticketstatushistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='ticket_attachments/%Y/%m/%d/')),
                ('file_size', models.IntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('uploaded_by_id', models.CharField(blank=True, max_length=64, null=True)),
                ('uploaded_by_name', models.CharField(blank=True, max_length=128, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
